name: technewsconciergemobile2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  auto_route: ^3.2.4
  build_runner: ^2.2.0

dev_dependencies:
  auto_route_generator: ^3.2.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

scripts: derry.yaml

flutter:

  uses-material-design: true
